### ISSUE TITLE
Your plugin for Comic Vine has been banned

### ISSUE THREAD

**Issue by edgework** [MediaBrowser/Emby.Plugins#104]
You need to update your plugin to respect our API usage guidelines. As written it does not. 

You may contact me for more info

**Comment by LukePulverenti** [comment]
Thanks.  I will just remove Comic Vine support for now until we have a chance to look at it.

**Comment by RedshirtMB** [comment]
I suspect they may have changed their api, but there is an issue in the BookProviderFromOpf that is causing books (not comics) with local metadata.opf files to error and then do look-ups on comic vine. If we could go back in time two years it would have been nice to have books and comics as two separate entities.
