### ISSUE TITLE
Trakt plugin sync issues

### ISSUE THREAD

**Issue by j2ghz** [MediaBrowser/Emby.Plugins#108]
I'm trying to determine the cause of wrong scrobbles, this plugins takes some episodes I've seen (marked as such on emby and on trakt) and scrobbles them as watched right now (about 100 of them)

Is this task https://github.com/MediaBrowser/Emby.Plugins/blob/master/Trakt/ScheduledTasks/SyncFromTraktTask.cs syncing or importing?
Here it says sync https://github.com/MediaBrowser/Emby.Plugins/blob/master/Trakt/ScheduledTasks/SyncFromTraktTask.cs#L375
Here it says import https://github.com/MediaBrowser/Emby.Plugins/blob/master/Trakt/ScheduledTasks/SyncFromTraktTask.cs#L367

**Comment by LukePulverenti** [comment]
That task syncs from trakt down to emby server, there is another process that syncs upwards. Ultimately, this plugin probably could use some restructuring to make everything just work and sync automatically without having to run jobs manually.
