### ISSUE TITLE
Getting error while browsing the files

### ISSUE THREAD

**Issue by incipio-srinu** [MediaBrowser/Emby.Plugins#41]
Hi all,

I am getting this issue in My mac mini when I requested to access the files in the Mac mini. Please find the error in the image
![screen shot 2015-01-13 at 4 24 32 pm](https://cloud.githubusercontent.com/assets/8664360/5719714/ea02e552-9b40-11e4-933d-3c4cfee773c5.png)

**Comment by incipio-srinu** [comment]
Could any one please help me to solve this issue?

**Comment by LukePulverenti** [comment]
I think we just don't know, sorry. Looks like some kind of environmental issue.

**Comment by incipio-srinu** [comment]
Ok could you please help me to resolve this issue

**Comment by SvenVandenbrande** [comment]
I don't know how mac works. But do you have also something like an event viewer (like windows).

**Comment by incipio-srinu** [comment]
Yes we have. Basically here the issue is it is launching one window and showing button for start and stop but when I click on start it is showing the above error

**Comment by SvenVandenbrande** [comment]
And do you see something in that event viewer?

**Comment by incipio-srinu** [comment]
it is launching one window and showing button for start and stop but when I click on start it is showing the above error

**Comment by incipio-srinu** [comment]
Could any one please help me to resolve this issue?

**Comment by SvenVandenbrande** [comment]
I don't have experience with mac. So I don't know where you can find some more information... :(

**Comment by incipio-srinu** [comment]
Any one please help me?

**Comment by incipio-srinu** [comment]
Hi after made some change I got an error that Invalid Path:/ . Any ideas/suggestions could be very helpful
